/**
 * Case 1 — "The Lighthouse". Free case.
 *
 * Design notes and the full claim table live in docs/case-1-design.md. Read that
 * before changing anything here: the prose exists to plant the claims, and the
 * claims are load-bearing. Moving a time window by ten minutes can silently
 * create a fourth contradiction or destroy one of the three.
 *
 * Times are minutes since the case epoch (day 1, 00:00). Ruth dies on day 1 at
 * roughly 22:10 = 1330. The threads you read are from the two days after.
 */
export const theLighthouseRaw = {
  id: 'the-lighthouse',
  title: 'The Lighthouse',
  blurb:
    'Your aunt kept the light at Ardnoe Point. They are calling it a fall. You have her phone, and everyone still has their story straight.',
  characters: [
    { id: 'you', name: 'You', avatarColor: '#2F6F4E' },
    { id: 'ruth', name: 'Ruth', avatarColor: '#8A7B5C' },
    { id: 'mairi', name: 'Mairi', avatarColor: '#C4483C' },
    { id: 'callum', name: 'Callum', avatarColor: '#4E8CF0' },
    { id: 'esme', name: 'Esme', avatarColor: '#6E5AA8' },
  ],
  places: [
    { id: 'point', name: 'Ardnoe Point' },
    { id: 'lighthouse', name: 'the lighthouse', parentId: 'point' },
    { id: 'path', name: 'the cliff path', parentId: 'point' },
    { id: 'harbour', name: 'the harbour' },
    { id: 'cafe', name: 'the café', parentId: 'harbour' },
    { id: 'slip', name: 'the slipway', parentId: 'harbour' },
    { id: 'cottage', name: 'the cottage' },
    { id: 'ferry', name: 'the ferry' },
  ],
  threads: [
    // ---------------------------------------------------------------- t-ruth
    {
      id: 't-ruth',
      title: 'Ruth',
      participantIds: ['you', 'ruth'],
      requiresContradictionIds: [],
      messages: [
        {
          id: 'r1',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1100,
          body: 'you actually got on it then',
        },
        {
          id: 'r2',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1104,
          body: 'last ferry. six years and the same man taking the tickets',
        },
        {
          id: 'r3',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1108,
          body: 'that will be wee Callum now. Mairi\'s boy. he was nine when you left',
        },
        {
          id: 'r4',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1112,
          body: 'dont come up tonight. its blowing a hoolie out here and the path is nothing but glass',
        },
        {
          id: 'r5',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1120,
          body: 'tomorrow then. you sound off',
        },
        {
          id: 'r6',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1131,
          body: 'im fine. theres a thing with the trust ill tell you about tomorrow when ive slept on it',
        },
        {
          id: 'r7',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1138,
          body: 'two years of books and a hole in the middle of them the size of a boat',
        },
        {
          id: 'r8',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1142,
          body: 'ruth. what does that mean',
        },
        {
          id: 'r9',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1150,
          body: 'it means i have to say something to someone i have known for forty years and i would rather walk into the sea',
        },
        {
          id: 'r10',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1156,
          body: 'ive told her. thats done. shes to come and see me tonight and then in the morning i go to the police whatever she says',
        },
        {
          id: 'r11',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1160,
          body: 'told WHO',
        },
        {
          id: 'r12',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1245,
          body: 'im away up the tower, the lamp is playing up again. forty years automated and it still wants a person standing beside it',
          claims: [
            {
              id: 'c-ruth-tower',
              subject: 'ruth',
              assertedBy: 'ruth',
              predicate: { kind: 'at_place', placeId: 'lighthouse' },
              window: { start: 1245, end: 1350 },
              sourceMessageId: 'r12',
              label: 'Ruth: up the tower, 20:45–22:30',
            },
          ],
        },
        {
          id: 'r13',
          threadId: 't-ruth',
          senderId: 'ruth',
          sentAt: 1252,
          body: 'dont worry about me. worry about the state of my spare room',
        },
        {
          id: 'r14',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1420,
          body: 'ruth?',
        },
        {
          id: 'r15',
          threadId: 't-ruth',
          senderId: 'you',
          sentAt: 1690,
          body: 'ruth please',
        },
      ],
    },

    // --------------------------------------------------------------- t-group
    {
      id: 't-group',
      title: 'Ardnoe',
      participantIds: ['you', 'mairi', 'callum', 'esme'],
      requiresContradictionIds: [],
      messages: [
        {
          id: 'g1',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 1985,
          body: 'For anyone who has not heard. Ruth was found at the foot of the tower stairs this morning. She is gone.',
        },
        {
          id: 'g2',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 1987,
          body: 'The café is open today for anyone who does not want to be in their own house. No charge. Just come.',
        },
        {
          id: 'g3',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 1994,
          body: 'christ',
        },
        {
          id: 'g4',
          threadId: 't-group',
          senderId: 'esme',
          sentAt: 2001,
          body: 'I am so sorry. I only met her three times and she still gave me a key to the tower so I could count seals from the gallery.',
        },
        {
          id: 'g5',
          threadId: 't-group',
          senderId: 'you',
          sentAt: 2010,
          body: 'i was on the boat over. she told me not to come up because of the path',
        },
        {
          id: 'g6',
          threadId: 't-group',
          senderId: 'you',
          sentAt: 2011,
          body: 'she told me not to come up',
        },
        {
          id: 'g7',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 2016,
          body: 'And she was right to. That path in that wind would have had you over too. Do not start on yourself.',
        },
        {
          id: 'g8',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 2024,
          body: 'the polis were down the slip this morning asking everyone where they were. felt weird for a fall',
        },
        {
          id: 'g9',
          threadId: 't-group',
          senderId: 'esme',
          sentAt: 2029,
          body: 'They have to. It is procedure with a sudden death, not an accusation. They asked me too.',
        },
        {
          id: 'g10',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 2033,
          body: 'aye well i told them straight. i brought the last boat in at eight with your aunt on it',
          claims: [
            {
              id: 'c-callum-ferry',
              subject: 'callum',
              assertedBy: 'callum',
              predicate: { kind: 'at_place', placeId: 'ferry' },
              window: { start: 1140, end: 1200 },
              sourceMessageId: 'g10',
              label: 'Callum: on the ferry, 19:00–20:00',
            },
          ],
        },
        {
          id: 'g11',
          threadId: 't-group',
          senderId: 'you',
          sentAt: 2036,
          body: 'you did. you carried my bag up the steps and i didnt say thank you',
          claims: [
            {
              id: 'c-you-ferry',
              subject: 'you',
              assertedBy: 'you',
              predicate: { kind: 'at_place', placeId: 'ferry' },
              window: { start: 1140, end: 1200 },
              sourceMessageId: 'g11',
              label: 'You: on the last ferry, 19:00–20:00',
            },
          ],
        },
        {
          id: 'g12',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 2041,
          body: 'and then i was down the slip from about twenty to ten till quarter past. the stern line had gone on her and i wasnt leaving it in that swell',
          claims: [
            {
              id: 'c-callum-slip',
              subject: 'callum',
              assertedBy: 'callum',
              predicate: { kind: 'at_place', placeId: 'slip' },
              window: { start: 1300, end: 1335 },
              sourceMessageId: 'g12',
              label: 'Callum: at the slipway, 21:40–22:15',
            },
          ],
        },
        {
          id: 'g13',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 2043,
          body: 'soaked to the skin by the end of it',
        },
        {
          id: 'g14',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 2050,
          body: 'Callum. Nobody needs the minute by minute.',
        },
        {
          id: 'g15',
          threadId: 't-group',
          senderId: 'callum',
          sentAt: 2052,
          body: 'im just saying what i told them',
        },
        {
          id: 'g16',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 2055,
          body: 'I know love. Not here though.',
        },
        {
          id: 'g17',
          threadId: 't-group',
          senderId: 'esme',
          sentAt: 2110,
          body: 'Whoever is handling the Trust — her survey notebook is still in the tower and it is not mine to take. Someone should tell the family.',
        },
        {
          id: 'g18',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 2118,
          body: 'I do the Trust books. I will see to it.',
        },
        {
          id: 'g19',
          threadId: 't-group',
          senderId: 'you',
          sentAt: 2125,
          body: 'she said there was a thing with the trust. the night she died. she said there was a hole in it',
        },
        {
          id: 'g20',
          threadId: 't-group',
          senderId: 'mairi',
          sentAt: 2131,
          body: 'She was tired and she was sixty one and the lamp had been failing for a month. Let her be tired.',
        },
      ],
    },

    // --------------------------------------------------------------- t-mairi
    {
      id: 't-mairi',
      title: 'Mairi Bell',
      participantIds: ['you', 'mairi'],
      requiresContradictionIds: [],
      messages: [
        {
          id: 'm1',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2140,
          body: 'You should not have found out in a group chat. That was my doing and I am sorry for it.',
        },
        {
          id: 'm2',
          threadId: 't-mairi',
          senderId: 'you',
          sentAt: 2149,
          body: 'she said she told someone about the books. she said shes to come and see me tonight',
        },
        {
          id: 'm3',
          threadId: 't-mairi',
          senderId: 'you',
          sentAt: 2150,
          body: 'she. you keep the books',
        },
        {
          id: 'm4',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2161,
          body: 'I keep the books because nobody else would do it for nothing. And yes she rang me about a column that did not add. I told her I would bring the folder up at the weekend.',
        },
        {
          id: 'm5',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2163,
          body: 'I did not go up there. I was in the café.',
          claims: [
            {
              id: 'c-mairi-cafe',
              subject: 'mairi',
              assertedBy: 'mairi',
              predicate: { kind: 'at_place', placeId: 'cafe' },
              window: { start: 1230, end: 1380 },
              sourceMessageId: 'm5',
              label: 'Mairi: in the café, 20:30–23:00',
            },
          ],
        },
        {
          id: 'm6',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2164,
          body: 'From half eight until I locked up at eleven. In the café, the whole evening, like every evening of my life.',
        },
        {
          id: 'm7',
          threadId: 't-mairi',
          senderId: 'you',
          sentAt: 2170,
          body: 'on your own?',
        },
        {
          id: 'm8',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2178,
          body: 'Callum was with me. He was in the café the whole night, from nine until we shut. So there is two of us saying it, if it is a witness you are after.',
          claims: [
            {
              id: 'c-callum-cafe',
              subject: 'callum',
              assertedBy: 'mairi',
              predicate: { kind: 'at_place', placeId: 'cafe' },
              window: { start: 1260, end: 1380 },
              sourceMessageId: 'm8',
              label: 'Callum: in the café, 21:00–23:00 (per Mairi)',
            },
          ],
        },
        {
          id: 'm9',
          threadId: 't-mairi',
          senderId: 'you',
          sentAt: 2185,
          body: 'i wasnt after a witness',
        },
        {
          id: 'm10',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2192,
          body: 'No. I know. Ignore me, I have not slept.',
        },
        {
          id: 'm11',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2201,
          body: 'You came in that night yourself, do you remember. Quarter past nine, before you went to hers. You had the tea and you did not touch it.',
          claims: [
            {
              id: 'c-you-cafe',
              subject: 'you',
              assertedBy: 'mairi',
              predicate: { kind: 'at_place', placeId: 'cafe' },
              window: { start: 1265, end: 1290 },
              sourceMessageId: 'm11',
              label: 'You: in the café, 21:05–21:30 (per Mairi)',
            },
          ],
        },
        {
          id: 'm12',
          threadId: 't-mairi',
          senderId: 'you',
          sentAt: 2205,
          body: 'i remember',
        },
        {
          id: 'm13',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2214,
          body: 'I cashed up at twenty to eleven, same as always, and the float was eleven pound down and I sat and counted it three times like it mattered.',
          claims: [
            {
              id: 'c-mairi-cashing',
              subject: 'mairi',
              assertedBy: 'mairi',
              predicate: { kind: 'doing', actionId: 'cashing_up', exclusiveGroup: 'mairi-late' },
              window: { start: 1355, end: 1380 },
              sourceMessageId: 'm13',
              label: 'Mairi: cashing up, 22:35–23:00',
            },
          ],
        },
        {
          id: 'm14',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2220,
          body: 'Eleven pound. And she was lying at the bottom of those stairs the whole time I was counting it.',
        },
        {
          id: 'm15',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2240,
          body: 'The girl in the cottage had her light on when I walked home after eleven. I remember thinking somebody else is awake.',
          claims: [
            {
              id: 'c-esme-cottage-late',
              subject: 'esme',
              assertedBy: 'mairi',
              predicate: { kind: 'at_place', placeId: 'cottage' },
              window: { start: 1380, end: 1440 },
              sourceMessageId: 'm15',
              label: 'Esme: at the cottage, 23:00–24:00 (per Mairi)',
            },
          ],
        },
        {
          id: 'm16',
          threadId: 't-mairi',
          senderId: 'mairi',
          sentAt: 2258,
          body: 'Come to the café tomorrow. I will feed you and you will let me, because that is what I have instead of anything useful to say.',
        },
      ],
    },

    // ---------------------------------------------------------------- t-esme
    {
      id: 't-esme',
      title: 'Esme Trian',
      participantIds: ['you', 'esme'],
      requiresContradictionIds: [],
      messages: [
        {
          id: 'e1',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2400,
          body: 'I hope this is not an intrusion. You said in the group that she told you not to come up. I wanted you to know she said the same to me that week.',
        },
        {
          id: 'e2',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2402,
          body: 'She was very firm about that path in weather. It was not a thing she was casual about, which is why the ruling bothers me.',
        },
        {
          id: 'e3',
          threadId: 't-esme',
          senderId: 'you',
          sentAt: 2411,
          body: 'bothers you how',
        },
        {
          id: 'e4',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2420,
          body: 'I keep a survey log. Times, positions, conditions, every night. It is habit and it is also the only reason I can tell you any of this precisely.',
        },
        {
          id: 'e5',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2423,
          body: 'I was in the cottage from seven until half nine writing up the afternoon count.',
          claims: [
            {
              id: 'c-esme-cottage',
              subject: 'esme',
              assertedBy: 'esme',
              predicate: { kind: 'at_place', placeId: 'cottage' },
              window: { start: 1140, end: 1290 },
              sourceMessageId: 'e5',
              label: 'Esme: at the cottage, 19:00–21:30',
            },
          ],
        },
        {
          id: 'e6',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2426,
          body: 'Then the wind dropped for about half an hour, which it does before it backs, and I went out onto the cliff path to get a last listen for the pups.',
          claims: [
            {
              id: 'c-esme-path',
              subject: 'esme',
              assertedBy: 'esme',
              predicate: { kind: 'at_place', placeId: 'path' },
              window: { start: 1300, end: 1330 },
              sourceMessageId: 'e6',
              label: 'Esme: on the cliff path, 21:40–22:10',
            },
          ],
        },
        {
          id: 'e7',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2430,
          body: 'Her lamp was lit up the tower the whole time I was out. I logged it at 21:40 and again at 22:00 because the beam is my timing mark.',
          claims: [
            {
              id: 'c-ruth-lamp',
              subject: 'ruth',
              assertedBy: 'esme',
              predicate: { kind: 'at_place', placeId: 'lighthouse' },
              window: { start: 1300, end: 1320 },
              sourceMessageId: 'e7',
              label: 'Ruth: up the tower, 21:40–22:00 (per Esme)',
            },
          ],
        },
        {
          id: 'e8',
          threadId: 't-esme',
          senderId: 'you',
          sentAt: 2436,
          body: 'you were on the path at the same time she was up there',
        },
        {
          id: 'e9',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2441,
          body: 'Yes. And I was not the only one on it.',
        },
        {
          id: 'e10',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2444,
          body: 'I passed Mairi Bell coming the other way at 21:47. I logged it because I log everything, and because I was surprised — she had a coat over her head and she went by me without a word.',
          claims: [
            {
              id: 'c-mairi-path',
              subject: 'mairi',
              assertedBy: 'esme',
              predicate: { kind: 'at_place', placeId: 'path' },
              window: { start: 1305, end: 1320 },
              sourceMessageId: 'e10',
              label: 'Mairi: on the cliff path, 21:45–22:00 (per Esme)',
            },
          ],
        },
        {
          id: 'e11',
          threadId: 't-esme',
          senderId: 'you',
          sentAt: 2450,
          body: 'shes telling everyone she was in the cafe all night',
        },
        {
          id: 'e12',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2458,
          body: 'Then one of us is wrong, and I have it written down at the time with a wind speed next to it. I am not saying what that means. I am saying I will not un-write it.',
        },
        {
          id: 'e13',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2470,
          body: 'I did tell the officer. He wrote it in the back of the notebook, after the part where he had already written "fall".',
        },
        {
          id: 'e14',
          threadId: 't-esme',
          senderId: 'esme',
          sentAt: 2480,
          body: 'I am here another six weeks. If you want the log, it is yours.',
        },
      ],
    },

    // -------------------------------------------------- t-callum-truth (gated)
    {
      id: 't-callum-truth',
      title: 'Callum',
      participantIds: ['you', 'callum'],
      requiresContradictionIds: ['x-callum-alibi', 'x-mairi-path'],
      messages: [
        {
          id: 'k1',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3010,
          body: 'you know dont you',
        },
        {
          id: 'k2',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3011,
          body: 'she told everyone i was in the cafe. i wasnt in the cafe. you can ask anyone who was down the slip that night',
        },
        {
          id: 'k3',
          threadId: 't-callum-truth',
          senderId: 'you',
          sentAt: 3019,
          body: 'why would she say it',
        },
        {
          id: 'k4',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3026,
          body: 'because if im in the cafe with her then nobody asks me anything. thats the whole reason. she wasnt covering for me. she was covering for herself and using me to do it',
        },
        {
          id: 'k5',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3034,
          body: 'i finished the line about quarter past ten and came up the back way past the point because its shorter',
        },
        {
          id: 'k6',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3040,
          body: 'she was at the lighthouse door. ten past ten, maybe a minute either side. i saw her in the beam when it came round',
          claims: [
            {
              id: 'c-mairi-door',
              subject: 'mairi',
              assertedBy: 'callum',
              predicate: { kind: 'at_place', placeId: 'lighthouse' },
              window: { start: 1325, end: 1335 },
              sourceMessageId: 'k6',
              label: 'Mairi: at the lighthouse door, 22:05–22:15 (per Callum)',
            },
          ],
        },
        {
          id: 'k7',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3043,
          body: 'i didnt shout. i dont know why. she was standing that still',
        },
        {
          id: 'k8',
          threadId: 't-callum-truth',
          senderId: 'you',
          sentAt: 3050,
          body: 'callum',
        },
        {
          id: 'k9',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3056,
          body: 'she came in after eleven wet through and she put her coat in the machine. mum has never washed a coat at night in her life',
        },
        {
          id: 'k10',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3062,
          body: 'and i have sat with that for two days and let her tell people i was beside her',
        },
        {
          id: 'k11',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3068,
          body: 'the money was mine. the hole in ruths books. it was for me. i didnt know where it came from and i didnt ask and thats the same as knowing isnt it',
        },
        {
          id: 'k12',
          threadId: 't-callum-truth',
          senderId: 'callum',
          sentAt: 3075,
          body: 'do what you have to do. i am not going to say it isnt true a second time',
        },
      ],
    },

    // -------------------------------------------------- t-mairi-again (gated)
    {
      id: 't-mairi-again',
      title: 'Mairi Bell',
      participantIds: ['you', 'mairi'],
      requiresContradictionIds: ['x-callum-alibi', 'x-mairi-path'],
      messages: [
        {
          id: 'n1',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3200,
          body: 'He has spoken to you. I can tell by how long you have not answered me.',
        },
        {
          id: 'n2',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3208,
          body: 'Alright. I walked out to the Point. I have said the café because the café is easier and because once you have said a thing to a policeman you have to keep saying it.',
        },
        {
          id: 'n3',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3212,
          body: 'I got as far as the gate and I turned round. I could not do it. I came home the long way so nobody would see my face.',
        },
        {
          id: 'n4',
          threadId: 't-mairi-again',
          senderId: 'you',
          sentAt: 3220,
          body: 'the gate',
        },
        {
          id: 'n5',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3224,
          body: 'The gate. Not the door. I never went near the door.',
        },
        {
          id: 'n6',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3231,
          body: 'She was going to take him from me. Not the money — she could have had the money, I would have sold the café. She was going to put his name in it.',
        },
        {
          id: 'n7',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3238,
          body: 'Forty years I have known her and she could not give me the one morning.',
        },
        {
          id: 'n8',
          threadId: 't-mairi-again',
          senderId: 'mairi',
          sentAt: 3246,
          body: 'Whatever my son has told you, he was at the slipway in the dark and the beam plays tricks out there. Ask anyone. Ask him again tomorrow.',
        },
      ],
    },
  ],
  /**
   * One motive, established by two messages that already existed.
   *
   * Ruth names the hole in the Trust books before she dies (r7); Callum says
   * whose it was (k11), and his thread only opens once the first two
   * contradictions are proven. So the reason arrives after the alibi breaks,
   * which is the order the story wants — and it cannot be stumbled into from
   * the board, because it is earned by reading.
   */
  motives: [
    {
      id: 'm-trust',
      characterId: 'mairi',
      summary:
        'She had been taking from the Ardnoe Light Trust for two years to cover Callum\'s debts, and Ruth had found the hole in the books that week.',
      establishedByMessageIds: ['r7', 'k11'],
    },
  ],
  contradictions: [
    {
      id: 'x-callum-alibi',
      claimIdA: 'c-callum-cafe',
      claimIdB: 'c-callum-slip',
      revelation:
        'Callum could not have been mending a line at the slipway and sitting in his mother\'s café at the same time. He put himself at the slip freely, in front of everyone, before she said otherwise — so the false half is hers. She gave her son an alibi he never asked for, which means she needed him not to be asked.',
    },
    {
      id: 'x-mairi-path',
      claimIdA: 'c-mairi-cafe',
      claimIdB: 'c-mairi-path',
      revelation:
        'She put herself behind the counter from half eight until eleven. At 21:47 a woman with a survey log and no stake in this passed her on the cliff path, going the other way, with a coat over her head. The café was not an alibi. It was a place to put herself.',
    },
    {
      id: 'x-mairi-door',
      claimIdA: 'c-mairi-cafe',
      claimIdB: 'c-mairi-door',
      revelation:
        'The path could still have been a walk to clear her head. The door cannot. At ten past ten she was standing at the foot of the tower, lit up by her friend\'s own lamp — at the minute Ruth stopped answering, and an hour before she came home and washed a coat she had never washed at night in her life.',
    },
  ],
  solution: {
    killerId: 'mairi',
    requiredContradictionIds: ['x-callum-alibi', 'x-mairi-path', 'x-mairi-door'],
    // Breaking the alibi is not enough. You have to be able to say why.
    requiredMotiveIds: ['m-trust'],
    epilogue:
      'She did not deny it when they came. She asked whether Callum would have to stand up in a room and say it out loud, and when they told her he would, she said the whole thing herself so that he would not have to.\n\nThe Trust was eleven thousand pounds short. Ruth had written it all out in the back of the survey notebook, in her own hand, with the date she meant to go to the police. She had also written, underneath: "M. has been my friend since we were five. Ask them to be kind to her."\n\nThey took the lamp out that winter. Nobody had been asked to stand beside it for forty years.',
  },
};
